[supabase]
project_id = "hexamind-stripe"
plan = "free"

[auth]
enabled = true

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
postgres_version = 15
major_version = 15

[analytics]
enabled = true
port = 54322

[functions]
enabled = true
deno = "1.40.0"
verify_jwt = false
import_map = "./supabase/functions/import_map.json"
